[workspace]
members = ["configuration", "llm-composer", "llm-selector", "server", "token-measure"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
configuration = { path = "configuration" }
llm-composer = { path = "llm-composer" }
llm-selector = { path = "llm-selector" }
server = { path = "server" }
token-measure = { path = "token-measure" }

tracing = "0.1.44"
tracing-subscriber = "0.3.22"

async-trait = "0.1.89"
tokio = "1.49.0"

serde = "1.0.228"
toml = "0.9.10"

redis = "1.0.3"

futures = "0.3"
genai = "0.5.1"

actix-web = "4.12.1"
actix-web-httpauth = "0.8.2"

uuid = "1.21.0"
base64 = "0.22.1"
chrono = "0.4.43"

clap = "4.5.57"

[package]
name = "ayatori"
version = "0.2.1"
edition.workspace = true
license.workspace = true

[dependencies]
configuration.workspace = true
llm-selector.workspace = true
server.workspace = true
token-measure.workspace = true

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

serde = { workspace = true, features = ["derive"] }
toml.workspace = true

clap = { workspace = true, features = ["derive"] }

tokio = { workspace = true, features = ["full"] }
