[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
llm-responses.workspace = true
llm-selector.workspace = true
token-measure.workspace = true

actix-web = { workspace = true, features = ["rustls-0_23"] }
actix-web-httpauth.workspace = true
rustls = "*"
serde = { version = "1.0.228", features = ["derive"] }
uuid = { workspace = true, features = ["v4"] }
base64.workspace = true
chrono.workspace = true
tracing.workspace = true
futures.workspace = true
serde_json = "1"
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
actix-http = "3"
configuration.workspace = true
wiremock = "0.6"
