name: Run tests and lints
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache build
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-test-

      - name: Run tests
        shell: bash
        run: |
          cargo test --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache build
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-lint-

      - name: Run clippy
        shell: bash
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace -- -D warnings

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache build
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-license-

      - name: Install cargo deny check
        shell: bash
        run: |
          cargo install --locked cargo-deny

      - name: Run cargo deny check
        shell: bash
        run: |
          cargo deny check
