name: Run tests and lints
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-test-

      - name: Run tests
        shell: bash
        run: |
          cargo test --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-lint-

      - name: Run clippy
        shell: bash
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace -- -D warnings

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-license-

      - name: Install cargo deny check
        shell: bash
        run: |
          cargo install --locked cargo-deny

      - name: Run cargo deny check
        shell: bash
        run: |
          cargo deny check
