name: Run tests and lints
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache build
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-test-

      - name: Run tests
        shell: bash
        run: |
          cargo test --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache build
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-lint-

      - name: Run clippy
        shell: bash
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace -- -D warnings

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache build
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-license-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-license-

      - name: Install cargo deny check
        shell: bash
        run: |
          cargo install --locked cargo-deny

      - name: Run cargo deny check
        shell: bash
        run: |
          cargo deny check
